### ISSUE TITLE
M1 MAC ? [CLOSED] [FIXED]

### ISSUE THREAD

**Issue by Snowyodz** [tobspr/RenderPipeline-Samples#7]
Does this not support M1 MACBOOKS ? Following error ⬇️ 
`ERROR: Compute shaders not supported! Please update your driver, or get a newer gpu.`

Once opened the trouble shoot page I see no help on mac!

**Comment by rdb** [comment]
Duplicate of tobspr/RenderPipeline#108

**Comment by Snowyodz** [comment]
> Duplicate of [tobspr/RenderPipeline#108](https://github.com/tobspr/RenderPipeline/issues/108)

Oh thank's it's kinda sad tho
